import Head from 'next/head'
import { useEffect, useState } from 'react';
import Main from '../components/Main';
import { filterByRegion,filterCountries } from '../assets/utils/funcs';
import Searchbar from '../components/Searchbar';
import { Country } from '../assets/utils/types';

export default function Home() {
  const [countries, setCountries] = useState<Country[]>([]);
  const [search, setSearch] = useState<string>('');
  const [filteredCountries, setFilteredCountries] = useState<Country[]>(countries);  
  const [region, setRegion] = useState<string>('');

  console.log(countries);
  
  
  useEffect(() => {
    const fetchCountries = async () => {
      const res = await fetch("https://restcountries.com/v3.1/all");
      const data = await res.json();
      setCountries(data);
    };
    fetchCountries();
  }, []);

  useEffect(() => {
    setFilteredCountries(filterCountries(countries, search));
  },[countries, search])

  useEffect(() => {
    setFilteredCountries(filterByRegion(countries, region));
  },[countries,region])

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Searchbar 
        setRegion={setRegion}
        setSearch={setSearch}
        />
        <Main 
        countries={filteredCountries}
        />
      </main>
    </div>
  )
}
